//ALERT TYPES
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
//AUTHENTICATION TYPES
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOAD_USER = 'LOAD_USER';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
//PROFILE TYPES
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
//PORTFOLIO TYPES
export const GET_PORTFOLIO = 'GET_PORTFOLIO';
export const PORTFOLIO_ERROR = 'PORTFOLIO_ERROR';
export const CLEAR_PORTFOLIO = 'CLEAR_PORTFOLIO';
//ACCOUNT TYPES
export const GET_ACCOUNT = 'GET_ACCOUNT';
export const ACCOUNT_ERROR = 'ACCOUNT_ERROR';
export const CLEAR_ACCOUNT = 'CLEAR_ACCOUNT';

export const SET_LOADING = 'SET_LOADING';
